// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MetuljmaniaDatabase.Models.DbModels
{
    public partial class Event
    {
        public Event()
        {
            Pilot = new HashSet<Pilot>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int Year { get; set; }

        public virtual ICollection<Pilot> Pilot { get; set; }
    }
}